Production/Controllers/PermissionController.cs
using Production.Business;
using Production.DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace production.Controllers
{
    public class PermissionController : Controller
    {
        PermissionBL PermissionBL = new PermissionBL();

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult _List(Permission model)
        {
            var list = PermissionBL.GetList(model);
            return PartialView(list);
        }
        public ActionResult Edit(int PermissionID)
        {
            Permission cust = PermissionBL.GetById(PermissionID);
            return PartialView(cust);
        }
        public ActionResult Save(Permission model)
        {
            var data = PermissionBL.Save(model);
            if (data.PermissionID == -1)
                return Json(new { result = "failed", message = "PermissionID duplicated." });

            return Json(new { result = "ok"});
        }
        public ActionResult Delete(int PermissionID)
        {
            PermissionBL.Delete(PermissionID);
            return Json(new { result = "ok" });
        }

    }
}

Production/Views/Permission/Edit.cshtml
@model Production.DataAccess.Permission

@*<script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>*@

@using (Html.BeginForm("Save", "Permission", FormMethod.Post, new { @class = "my_form", id = "frmEdit" })) {
    @Html.HiddenFor(model => model.OldPermissionID)
    @Html.HiddenFor(model => model.IsCreate)
    <div class="editor-label">
        @Html.LabelFor(model => model.PermissionID, ResourceBL.GetText("Permission ID"))
    </div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.PermissionID, new { @class = "form-control digits" })
        @Html.ValidationMessageFor(model => model.PermissionID)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.PermissionName, ResourceBL.GetText("Permission Name"))
    </div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.PermissionName, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.PermissionName)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.Description, ResourceBL.GetText("Description"))
    </div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.Description, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Description)
    </div>
    <br />
    <p>
        <input class="btn btn-sm" type="button" value="Save" onclick="saveItem()" />
        <a href="javascript: void(0)" class="btn btn-sm" data-dismiss="modal" id="btnCancelEditOrder">
            @ResourceBL.GetText("Cancel")
        </a>
    </p>
}

Production/Views/Permission/Index.cshtml
@model List<Customer>

<div class="sub-title">
    @ResourceBL.GetText("Permissions")
</div>
<div class="">
    <div id="frmSearh" class="form-row pressenter" enter-handler="searchItems()">
        <div class="col-md-3 pb-2">
            <input type="text" placeholder="@ResourceBL.GetText("Permission")" class="form-control" id="txtPermissionName">
        </div>
        <div class="col-md-3 pb-2">
            <button type="button" class="btn btn-sm" onclick="searchItems()">@ResourceBL.GetText("Search")</button>
        </div>
    </div>
</div>
<div class="pull-right form-group">
    <a class="btn btn-sm" href="javascript: void(0);" onclick="editItem(0)">
        @ResourceBL.GetText("Add")
    </a>
</div>
<div id="dvItems">
    @{Html.RenderAction("_List", "Permission");}
</div>
@section Scripts
{
    <script type="text/javascript">


        var config = {
            sortBy: "",
            sortDirection: "DESC",
            page: 1
        };

        function sortBy(dCol) {
            if (config.sortBy == dCol) {
                if (config.sortDirection == "asc")
                    config.sortDirection = "desc";
                else
                    config.sortDirection = "asc";
            }
            else {
                config.sortBy = dCol;
                config.sortDirection = "asc";
            }

            searchItems();
        }

        function searchItems() {

            $.ajax({
                type: "POST",
                url: "@Url.Action("_List", "Permission")",
                data: {
                    sortBy: config.sortBy,
                    sortDirection: config.sortDirection,
                    pageSize: 10,
                    PermissionName: $("#txtPermissionName").val()
                },
                success: function (html) {
                    $("#dvItems").html(html);
                }
            });
        };
        function editItem(id) {
            if ($("#dvEdit").length == 0) {
                $("body").append("<div style='display:none' id='dvEdit'></div>");
            }
            var data = {
                PermissionID: id
            }
            if (id == 0)
                data.IsCreate = 1;

            $.ajax({
                type: "GET",
                url: "@Url.Action("Edit", "Permission")",
                data: {
                    PermissionID: id
                },
                success: function (html) {
                    $("#dvEdit").html(html);
                    $("#dvEdit").popupModal();
                }
            });
        }
        function saveItem(callback) {
            if ($("#frmEdit").valid()) {

                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Save", "Permission")",
                    data: $("#frmEdit").serialize(),
                    success: function (data) {
                        if (data.result == "ok") {
                            searchItems();
                            //$("#btnCancel").click();
                            $(".modal").modal("hide");
                            if (callback)
                                callback();
                        }
                        else {
                            showDialog(data.message);
                        }
                        
                    }
                });
            }
        };
        function deleteItem(id) {
            if (confirm("Do you want to delete this action?") == true) {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Delete", "Permission")",
                    data: {
                        PermissionID: id
                    },
                    success: function (data) {
                        if (data.result === "ok") {
                            searchItems();
                        }
                        else {
                            //alert(data.ErrorMessage);
                            showMessage({ content: data.message });
                        }

                    }
                });//End: $.ajax()
            }
        }

    </script>
}

Production/Views/Permission/_List.cshtml
@model IPagedList<Production.DataAccess.Permission>


<table style="width: 100%; margin-bottom: 15px;" class="table table-striped" id="tblRegistration">
    <thead>
        <tr>
            <th>
                <a href="#" onclick="sortBy('PermissionID'); return false;">@ResourceBL.GetText("PermissionID")</a>
            </th>
            <th>
                <a href="#" onclick="sortBy('PermissionName'); return false;">@ResourceBL.GetText("Permission Name")</a>
            </th>
            <th>
                <a href="#" onclick="sortBy('Description'); return false;">@ResourceBL.GetText("Description")</a>
            </th>            
            <th>
                <span href="#">@ResourceBL.GetText("Actions")</span>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
        <tr>
            <td>
                @Html.Raw(item.PermissionID)
            </td>
            <td>
                @Html.Raw(item.PermissionName)
            </td>
            <td>
                @Html.Raw(item.Description)
            </td>
            <td>
                <i class="fa fa-edit"></i><a href="javascript:void(0);" onclick="editItem(@item.PermissionID)">@ResourceBL.GetText("Edit")</a> |
                <i class="fa fa-remove"></i><a href="javascript:void(0);" onclick="deleteItem(@item.PermissionID)">@ResourceBL.GetText("Delete")</a>
            </td>
        </tr>
        }
    </tbody>
</table>

@if (Model.PageCount > 1) {
    <div class="paging">
        @Html.Pager(Model.PageSize, Model.PageIndex + 1, Model.TotalItemCount, new AjaxOptions() { UpdateTargetId = "dvUsers" }).Options(o => o
        .RouteValues(new
        {
            pageSize = ViewBag.pageSize
        }))
    </div>
}