Production/Controllers/ActionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Production.Business.Utilities;
using Production.DataAccess;
using Production.Business;
using System.Web.Caching;
using System.Collections;

namespace production.Controllers
{
    
    public class ActionsController : Controller
    {
        ActionBL actionBL = new ActionBL();
        CustomerBL customerBL = new CustomerBL();
        public ActionResult Index()
        {
            ViewBag.actions = ActionBL.GetMasterList();
            ViewBag.customers = customerBL.GetList();
            return View();
        }
        public ActionResult _List(Actions act, Order filter)
        {
            act.Order = filter;
            var actions = actionBL.GetList(act);
            return PartialView(actions);
        }

        public ActionResult Edit(Actions act)
        {
            ViewBag.Actions = ActionBL.GetMasterList();
            ViewBag.Farms = FarmBL.GetList();
            ViewBag.Units = UnitBL.GetList();
            ViewBag.Crops = CropBL.GetList();
            ViewBag.Varieties = VarietyBL.GetList();
            ViewBag.Orders = new OrderBL().GetList();
            var actions = actionBL.GetById(act);
            return PartialView(actions);
        }
        public ActionResult ClearCache()
        {            
            foreach (DictionaryEntry entry in HttpContext.Cache) {
                HttpContext.Cache.Remove(entry.Key.ToString());
            }
            return Json(new {result="ok"},JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Save(Actions model)
        {
            if (model.ID == 0) {
                model.UserID = SessionUtilities.CurrentUser.UserID;
                model.CreatedDate = DateTime.Now;
            }
            else {
                model.CreatedDate = model.CreatedDate ?? DateTime.Now;
                model.UserID = SessionUtilities.CurrentUser.UserID;
            }


            model = actionBL.Save(model);
            return Json(model);
        }
        public ActionResult Delete(int Id)
        {
            actionBL.Delete(Id);
            return Json(new { result = "ok", message = "" });
        }


    }
}

Production/Views/Actions/Edit.cshtml
@model Actions
@using Newtonsoft.Json;
@{
    ViewBag.Title = "Edit";
}

<form id="frmEdit">
    @Html.HiddenFor(model => model.ID)
    @Html.HiddenFor(model => model.CreatedDate)

    <div class="row form-group">
        <div class="col-sm-3 ">
            @Html.LabelFor(model => model.ActionID, ResourceBL.GetText("Action"), new { @class = "text-bold" })
        </div>
        <div class="col-sm-9">
            @Html.DropDownList("ActionID", new SelectList(ViewBag.Actions, "ActionID", "ActionName", Model.ActionID), ResourceBL.GetText("Select Phase"), new { @class = "form-control required" })
            @Html.ValidationMessageFor(model => model.FarmID)
        </div>
    </div>

    <div class="row form-group">
        <div class="col-sm-3 ">
            @Html.LabelFor(model => model.FarmID, ResourceBL.GetText("Farm"), new { @class = "text-bold" })
        </div>
        <div class="col-sm-9">
            @Html.DropDownList("FarmID", new SelectList(ViewBag.Farms, "FarmID", "FarmNumber", Model.FarmID), ResourceBL.GetText("Select Farm"), new { @class = "form-control required" })
            @Html.ValidationMessageFor(model => model.FarmID)
        </div>
    </div>
    <div class="row form-group">
        <div class="col-sm-3 ">
            @Html.LabelFor(model => model.OwnerID, ResourceBL.GetText("Owner"), new { @class = "text-bold" })
        </div>
        <div class="col-sm-9">
            @Html.DropDownList("OwnerID", new SelectList(ViewBag.Units, "OwnerID", "FirstName", Model.OwnerID), ResourceBL.GetText("Select Owner"), new { @class = "form-control required" })
            @Html.ValidationMessageFor(model => model.OwnerID)
        </div>
    </div>
    <div class="row form-group">
        <div class="col-sm-3 ">
            @Html.LabelFor(model => model.StepNumber, ResourceBL.GetText("Phase"), new { @class = "text-bold" })
        </div>
        <div class="col-sm-9">
            @Html.TextBox("StepNumber", Model.StepNumber, new { @class = "form-control required " })
            @Html.ValidationMessageFor(model => model.Name)
        </div>
    </div>
    <div class="row form-group">
        <div class="col-sm-3 ">
            @Html.LabelFor(model => model.OrderID, ResourceBL.GetText("Order"), new { @class = "text-bold" })

        </div>
        <div class="col-sm-9 ">
            <a href="javascript:void(0)"><i class="fa fa-list fa-2x"></i></a>
            @Html.DropDownList("OrderID", new SelectList(ViewBag.Orders, "OrderID", "OrderNo", Model.OrderID), ResourceBL.GetText("SelectOrder"), new { @class = "form-control required" })
            @Html.ValidationMessageFor(model => model.OrderID)
        </div>


    </div>
    <div class="row form-group">
        <div class="col-sm-3 ">
            @Html.LabelFor(model => model.CropID, ResourceBL.GetText("Crop"), new { @class = "text-bold" })
        </div>
        <div class="col-sm-9">
            @Html.DropDownList("CropID", new SelectList(ViewBag.Crops, "CropID", "CropCode", Model.CropID), ResourceBL.GetText("SelectCrop"), new { @class = "form-control required" })
            @Html.ValidationMessageFor(model => model.CropID)
        </div>
    </div>
    <div class="row form-group">
        <div class="col-sm-3 ">
            @Html.LabelFor(model => model.VarietyID, ResourceBL.GetText("Variety"), new { @class = "text-bold" })
        </div>
        <div class="col-sm-9">
            @Html.DropDownList("VarietyID", new SelectList(ViewBag.Varieties, "VarietyID", "VarietyCode"), ResourceBL.GetText("SelectVariety"), new { @class = "form-control required", onchange = "" })
            @Html.ValidationMessageFor(model => model.VarietyID)
        </div>
    </div>
    @*<div class="row form-group">
            <div class="col-sm-3 ">
                @Html.LabelFor(model => model.ActionDate, ResourceBL.GetText("Action Date"), new { @class = "text-bold" })
            </div>
            <div class="col-sm-9">
                @Html.TextBox("ActionDate", Model.ActionDate, new { @class = "form-control required number" })
                @Html.ValidationMessageFor(model => model.ActionDate)
            </div>
        </div>*@
    <div class="row form-group">
        <div class="col-sm-3 ">
            @Html.LabelFor(model => model.PlantNumber, ResourceBL.GetText("Plant Number"), new { @class = "text-bold" })
        </div>
        <div class="col-sm-9">
            @Html.TextBox("PlantNumber", Model.PlantNumber, new { @class = "form-control required number", onchange = "changeVariety()" })
            @Html.ValidationMessageFor(model => model.PlantNumber)
        </div>
    </div>
    <div class="row form-group">
        <div class="col-sm-3 ">
            @Html.LabelFor(model => model.HouseNumber, ResourceBL.GetText("House Number"), new { @class = "text-bold" })
        </div>
        <div class="col-sm-9">
            @Html.TextBox("HouseNumber", Model.HouseNumber, new { @class = "form-control required number" })
            @Html.ValidationMessageFor(model => model.HouseNumber)
        </div>
    </div>
    <div class="row form-group">
        <div class="col-sm-3 ">
            @Html.LabelFor(model => model.Note, ResourceBL.GetText("Note"), new { @class = "text-bold" })
        </div>
        <div class="col-sm-9">
            @Html.TextArea("Note", Model.Note, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Note)
        </div>
    </div>
    <div class="row form-group py-3">
        <div class="col-sm-3 ">
        </div>
        <div class="col-sm-9">
            <input type="button" class="btn btn-sm btn-success" value="@ResourceBL.GetText("Save")" onclick="saveAction()" />
            <a href="javascript: void(0)" class="btn btn-sm" data-dismiss="modal" id="btnCancel">
                @ResourceBL.GetText("Cancel")
            </a>
        </div>
    </div>
</form>

<script type="text/javascript">
    var vm = @Html.Raw(JsonConvert.SerializeObject(Model));
    function saveAction(callback) {
        if ($("#frmEdit").valid()) {

            $.ajax({
                type: "POST",
                url: "@Url.Action("Save", "Actions")",
                data: $("#frmEdit").serialize(),
                success: function (data) {
                    searchActions();
                    $("#btnCancel").click();
                    if (callback)
                        callback();
                }
            });
        }
    };
</script>

Production/Views/Actions/Index.cshtml
@{
    var actions = new List<Production.DataAccess.ActionMaster>(ViewBag.actions);
    var customers = new List<Production.DataAccess.Customer>(ViewBag.customers);
}

<div class="sub-title">
    @ResourceBL.GetText("Actions")
</div>
<div class="blocktitle">Search</div>
<div class="blockcontent">
    <div class="form-row pressenter" enter-handler="searchActions()">
        <div class="col-md-3 pb-2">
            @*<label for="CustomerID">&nbsp;</label>*@
            @Html.DropDownList("ddActionID", new SelectList(actions, "ActionID", "ActionName"), ResourceBL.GetText("Selectaction"), new { @class = "form-control" })
        </div>
        <div class="col-md-3 pb-2">
            @*<label for="OrderNo">@ResourceBL.GetText("OrderNo")</label>*@
            <input type="text" placeholder="@ResourceBL.GetText("OrderNo")" class="form-control" id="filterOrderNo">
        </div>
        <div class="col-md-3 pb-2">
            @*<label for="CustomerID">&nbsp;</label>*@
            @Html.DropDownList("ddCustomerID", new SelectList(customers, "CustomerID", "CustomerName"), "Select Customer", new { @class = "form-control" })
        </div>
        <div class="col-md-3 pb-2">
            @*<label for="OrderNo">&nbsp;</label>*@
            <button type="button" class="btn btn-sm" onclick="searchActions()">@ResourceBL.GetText("Search")</button>
        </div>

    </div>
</div>


<div class="pull-left form-group">
    <a class="btn btn-sm" href="javascript: void(0);" onclick="editItem(0)">
        <i class="fa fa-plus"></i> @ResourceBL.GetText("Add")
    </a>
</div>
<div id="dvActions">
    @{Html.RenderAction("_List", "Actions");}
</div>

@section Scripts
{
    <script type="text/javascript">
        $(document).ready(function () {

            $("#btnSearch").click(function () {
                searchActions();
            }).click();//End: $("#btnSearch").click();
        });//End: $(document).ready()

        var orderConfig = {
            sortBy: "OrderID",
            sortDirection: "DESC",
            page: 1
        };

        function sortBy(dCol) {
            if (orderConfig.sortBy == dCol) {
                if (orderConfig.sortDirection == "asc")
                    orderConfig.sortDirection = "desc";
                else
                    orderConfig.sortDirection = "asc";
            }
            else {
                orderConfig.sortBy = dCol;
                orderConfig.sortDirection = "asc";
            }

            searchActions();
        }

        function searchActions() {
            //orderConfig.page = getCurrentPageIndex();

            $.ajax({
                type: "get",
                url: "@Url.Action("_List", "Actions")",
                data: {
                    searchKey: $("#ddlSearchKey").val(),
                    searchValue: $.trim($("#txtSearchValue").val()),
                    sortBy: orderConfig.sortBy,
                    sortDirection: orderConfig.sortDirection,
                    pageSize: 10,                    
                    OrderNo: $("#filterOrderNo").val(),
                    CustomerID: $("#ddCustomerID").val(),
                    ActionID: $("#ddActionID").val()
                },
                success: function (html) {
                    $("#dvActions").html(html);
                }
            });
        };
        function editItem(id) {
            if ($("#dvEdit").length == 0) {
                $("body").append("<div style='display:none' id='dvEdit'></div>");
            }

            $.ajax({
                type: "GET",
                url: "@Url.Action("edit", "Actions")",
                data: {
                    id: id,
                },
                success: function (html) {
                    $("#dvEdit").html(html);

                    $("#dvEdit").popupModal({
                        //fullscreen: 'modal-fullscreen'
                        ///title: "Thêm Mới/Sửa"
                    });                    
                }
            });
        }
        function deleteItem(id) {
            if (confirm("Do you want to delete this action?") == true) {
                $.ajax({
                    type: "post",
                    url: "@Url.Action("Delete", "Actions")",
                    data: {
                        id: id
                    },
                    success: function (data) {
                        if (data.result === "ok") {
                            searchActions();
                        }
                        else {
                            //alert(data.ErrorMessage);
                            showMessage({ content: data.message });
                        }

                    }
                });//End: $.ajax()
            }
        }

    </script>
 }

Production/Views/Actions/_List.cshtml
@model MvcPaging.IPagedList<Actions>

<table style="width: 100%; margin-bottom: 15px;" class="table table-striped table-bordered" id="tblPhase">
    <tr>
        <th>
            <a href="#" onclick="sortBy('CreatedDate'); return false;">@ResourceBL.GetText("Created Date")</a>
        </th>
        <th>
            <a href="#" onclick="sortBy('Variety'); return false;">@ResourceBL.GetText("Variety")</a>
        </th>
        <th>
            <a href="#" onclick="sortBy('OrderNo'); return false;">@ResourceBL.GetText("OrderNo")</a>
        </th>
        <th>
            <a href="#" onclick="sortBy('ActionName'); return false;">@ResourceBL.GetText("Action")</a>
        </th>
        <th>
            <span href="#">@ResourceBL.GetText("Actions")</span>
        </th>
    </tr>
@foreach (var item in Model) {
    <tr>
        <td>
            @item.CreatedDate
        </td>
        <td>
            @item.Variety.VarietyCode
        </td>
        <td>
            @item.Order.OrderNo
        </td>
        <td>
            @item.ActionName
        </td>
        <td>
            <i class="fa fa-edit"></i> <a href="javascript:void(0);" onclick="editItem(@item.ID)">@ResourceBL.GetText("Edit")</a> |
            <i class="fa fa-remove"></i> <a href="javascript:void(0);" onclick="deleteItem(@item.ID)">@ResourceBL.GetText("Delete")</a>
        </td>
    </tr>
}

</table>