Production/Controllers/CropController.cs
using Production.Business;
using Production.DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace production.Controllers
{
    public class CropController : Controller
    {
        CropBL cropBL = new CropBL();

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult _List(Crop model)
        {
            var list = cropBL.GetList(model);
            return PartialView(list);
        }
        public ActionResult Edit(int CropID)
        {
            ViewBag.Customers = new CustomerBL().GetList();
            Crop cust = cropBL.GetById(CropID);
            return PartialView(cust);
        }
        public ActionResult Save(Crop model)
        {
            return Json(cropBL.Save(model));
        }
        public ActionResult Delete(int CropID)
        {
            cropBL.Delete(CropID);
            return Json(new { result = "ok" });
        }

    }
}

Production/Controllers/FarmController.cs
using Production.Business;
using Production.DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace production.Controllers
{
    public class FarmController : Controller
    {
        FarmBL farmBL = new FarmBL();

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult _List(Farm model)
        {
            var list = farmBL.GetList(model);
            return PartialView(list);
        }
        public ActionResult Edit(int FarmID)
        {
            Farm cust = farmBL.GetById(FarmID);
            return PartialView(cust);
        }
        public ActionResult Save(Farm model)
        {
            return Json(farmBL.Save(model));
        }
        public ActionResult Delete(int FarmID)
        {
            farmBL.Delete(FarmID);
            return Json(new { result = "ok" });
        }

    }
}

Production/Controllers/RoleController.cs
using Production.Business;
using Production.DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace production.Controllers
{
    public class RoleController : Controller
    {
        RoleBL RoleBL = new RoleBL();

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult _List(Role model)
        {
            var list = RoleBL.GetList(model);
            return PartialView(list);
        }
        public ActionResult Edit(int RoleID)
        {
            ViewBag.Permissions = PermissionBL.GetList();
            Role cust = RoleBL.GetById(RoleID);
            return PartialView(cust);
        }
        public ActionResult Save(Role model)
        {
            return Json(RoleBL.Save(model));
        }
        public ActionResult Delete(int RoleID)
        {
            RoleBL.Delete(RoleID);
            return Json(new { result = "ok" });
        }

    }
}

Production/Controllers/UnitController.cs
using Production.Business;
using Production.DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace production.Controllers
{
    public class UnitController : Controller
    {
        UnitBL UnitBL = new UnitBL();

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult _List(Unit model)
        {
            var list = UnitBL.GetList(model);
            return PartialView(list);
        }
        public ActionResult Edit(int UnitID)
        {
            ViewBag.Farms = FarmBL.GetList();
            ViewBag.Users = UsersBL.GetList();
            Unit cust = UnitBL.GetById(UnitID);
            return PartialView(cust);
        }
        public ActionResult Save(Unit model)
        {
            return Json(UnitBL.Save(model));
        }
        public ActionResult Delete(int UnitID)
        {
            UnitBL.Delete(UnitID);
            return Json(new { result = "ok" });
        }

    }
}

Production/Views/Shared/_Layout.cshtml
@{
    var languageID = SessionUtilities.CurrentLanguageID;
    var userLogged = SessionUtilities.CurrentUser;
    
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    @*<link href="~/Content/style-root.min.css" rel="stylesheet" />*@
    @*@Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")*@
</head>
<body>
    <div class="navbar navbar-expand-lg navbar-dark bg-success container-fluid" style="">
        <a class="navbar-brand" href="#">
            <img src="~/Content/images/logo.png" title="Lam Tai Production" />
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse flex-md-column" id="navbarSupportedContent">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item p-0 @(SessionUtilities.CurrentLanguageID == 2 ? "active" : "")"><a class="nav-link @(SessionUtilities.CurrentLanguageID == 2 ? "bg-primary" : "")" href="javascript:void(0)" onclick="changeCurrentLanguage('2');">Tiếng Việt</a></li>
                <li class="nav-item p-0 @(SessionUtilities.CurrentLanguageID == 1 ? "active" : "")"><a class="nav-link @(SessionUtilities.CurrentLanguageID == 1 ? "bg-primary" : "")" href="javascript:void(0)" onclick="changeCurrentLanguage('1');">English</a></li>
                @if (SessionUtilities.IsLoggedIn()) {
                    <li class="nav-item">
                        <span class="ml-1 navbar-text active">Welcome @SessionUtilities.CurrentUser.FirstName</span>
                        <a class="d-inline nav-link" href="@Url.Action("Logout","Users")">Log out</a>
                    </li>
                }
                else {
                    <li class="nav-item"><a class="nav-link" href="@Url.Action("Login","Users")">Login</a></li>
                }
            </ul>
            @if (SessionUtilities.IsLoggedIn()) {
            <ul class="nav navbar-nav ml-auto">
                @if (SessionUtilities.HasPermission(Enums.Permissions.Orders)) {
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("","Order")">Orders</a>
                    </li>
                }
                @if (SessionUtilities.HasPermission(Enums.Permissions.Tasks)) {
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("","Actions")">Tasks</a>
                    </li>
                }
                @if (SessionUtilities.HasPermission(Enums.Permissions.Customers)) {
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("","Customer")">Customers</a>
                    </li>
                }
                @if (SessionUtilities.HasPermission(Enums.Permissions.Farms)) {
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("","Farm")">Farms</a>
                    </li>
                }
                @if (SessionUtilities.HasPermission(Enums.Permissions.Units)) {
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("","Unit")">Units</a>
                    </li>
                }
                @if (SessionUtilities.HasPermission(Enums.Permissions.Crops)) {
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("","Crop")">Crops</a>
                    </li>
                }
                @if (SessionUtilities.HasPermission(Enums.Permissions.Varieties)) {
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("","Variety")">Varieties</a>
                    </li>
                }
                @if (SessionUtilities.HasPermission(Enums.Permissions.Users)) {
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("","Users")">Users</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("","Role")">Roles</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("","Permission")">Permissions</a>
                    </li>
                }
                @if (SessionUtilities.HasPermission(Enums.Permissions.Reports)) {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Reports
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Green Report</a>
                            <a class="dropdown-item" href="#">Hazera Report</a>
                            <a class="dropdown-item" href="#">FIDO Report</a>
                            <a class="dropdown-item" href="#">Genetic Report</a>
                        </div>
                    </li>
                }
            </ul>
            }
        </div>
    </div>
    <div class="page-wrap container-fluid">
        <div class="page-content" style="">
            @RenderBody()
        </div>
    </div>
    <script type="text/javascript">
        var ValidatorMessages = {
            required: '@ResourceBL.GetText("gValidationRequired")',
            email: '@ResourceBL.GetText("gValidationEmail")',
            url: '@ResourceBL.GetText("gValidationUrl")',
            date: '@ResourceBL.GetText("gValidationDate")',
            digits: '@ResourceBL.GetText("gValidationDigits")',
            safe: '@ResourceBL.GetText("gValidationSafe")',
            datevalidation: '@ResourceBL.GetText("gValidationSafe")'
        };
        var SiteConfig = {
            Prefix: "@(Url.Action("", "", null, Request.Url.Scheme))",
        }
    </script>
    <script src="~/Scripts/jquery/jquery.min.js"></script>
    <script src="~/Scripts/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery-validate-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Content/bootstrap/js/popper.min.js"></script>
    <script src="~/Content/bootstrap/js/bootstrap.bundle.min.js"></script>

    <script src="~/Scripts/shared.js"></script>
    @* @Scripts.Render("~/bundles/jquery")*@
    @RenderSection("scripts", required: false)
</body>
</html>