Production/Controllers/VarietyController.cs
using Production.Business;
using Production.DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace production.Controllers
{
    public class VarietyController : Controller
    {
        VarietyBL VarietyBL = new VarietyBL();

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult _List(Variety model)
        {
            var list = VarietyBL.GetList(model);
            return PartialView(list);
        }
        public ActionResult Edit(int VarietyID)
        {
            ViewBag.Customers = new CustomerBL().GetList();
            Variety cust = VarietyBL.GetById(VarietyID);
            return PartialView(cust);
        }
        public ActionResult Save(Variety model)
        {
            return Json(VarietyBL.Save(model));
        }
        public ActionResult Delete(int VarietyID)
        {
            VarietyBL.Delete(VarietyID);
            return Json(new { result = "ok" });
        }

    }
}

Production/Views/Variety/Edit.cshtml
@model Production.DataAccess.Variety

@*<script src="~/Scripts/jquery-1.8.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>*@

@using (Html.BeginForm("Save", "Variety", FormMethod.Post, new { @class = "my_form", id="frmEdit" })) {



        @Html.HiddenFor(model => model.VarietyID)

        <div class="editor-label">
            @Html.LabelFor(model => model.VarietyName, ResourceBL.GetText("Variety Name"))
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.VarietyName, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.VarietyName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.VarietyCode, ResourceBL.GetText("Variety Code"))
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.VarietyCode, new {@class="form-control" })
            @Html.ValidationMessageFor(model => model.VarietyCode)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CustomerID, ResourceBL.GetText("Customer"))
        </div>
        <div class="editor-field">
            @Html.DropDownList("CustomerID",new SelectList(ViewBag.Customers, "CustomerID", "CustomerName", Model.CustomerID), ResourceBL.GetText("Customer"), new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CustomerID)
        </div>        
        <br/>
        <p>
            <input class="btn btn-sm" type="button" value="Save" onclick="saveItem()" />
            <a href="javascript: void(0)" class="btn btn-sm" data-dismiss="modal" id="btnCancelEditOrder">
                @ResourceBL.GetText("Cancel")
            </a>
        </p>
}

Production/Views/Variety/Index.cshtml
<div class="sub-title">
    @ResourceBL.GetText("Varietis")
</div>
<div class="">
    <div id="frmSearh" class="form-row pressenter" enter-handler="searchItems()">
        <div class="col-md-3 pb-2">
            <input type="text" placeholder="@ResourceBL.GetText("Variety")" class="form-control" id="txtVarietyName">
        </div>
        <div class="col-md-3 pb-2">
            <button type="button" class="btn btn-sm" onclick="searchItems()">@ResourceBL.GetText("Search")</button>
        </div>
    </div>
</div>
<div class="pull-right form-group">
    <a class="btn btn-sm" href="javascript: void(0);" onclick="editItem(0)">
        @ResourceBL.GetText("Add")
    </a>
</div>
<div id="dvItems">
    @{Html.RenderAction("_List", "Variety");}
</div>
@section Scripts
{
    <script type="text/javascript">


        var config = {
            sortBy: "",
            sortDirection: "DESC",
            page: 1
        };

        function sortBy(dCol) {
            if (config.sortBy == dCol) {
                if (config.sortDirection == "asc")
                    config.sortDirection = "desc";
                else
                    config.sortDirection = "asc";
            }
            else {
                config.sortBy = dCol;
                config.sortDirection = "asc";
            }

            searchItems();
        }

        function searchItems() {

            $.ajax({
                type: "POST",
                url: "@Url.Action("_List", "Variety")",
                data: {
                    sortBy: config.sortBy,
                    sortDirection: config.sortDirection,
                    pageSize: 10,
                    VarietyName: $("#txtVarietyName").val()
                },
                success: function (html) {
                    $("#dvItems").html(html);
                }
            });
        };
        function editItem(id) {
            if ($("#dvEdit").length == 0) {
                $("body").append("<div style='display:none' id='dvEdit'></div>");
            }

            $.ajax({
                type: "GET",
                url: "@Url.Action("Edit", "Variety")",
                data: {
                    VarietyID: id,
                },
                success: function (html) {
                    $("#dvEdit").html(html);
                    $("#dvEdit").popupModal();
                }
            });
        }
        function saveItem(callback) {
            if ($("#frmEdit").valid()) {

                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Save", "Variety")",
                    data: $("#frmEdit").serialize(),
                    success: function (data) {
                        searchItems();
                        //$("#btnCancel").click();
                        $(".modal").modal("hide");
                        if (callback)
                            callback();
                    }
                });
            }
        };
        function deleteItem(id) {
            if (confirm("Do you want to delete this action?") == true) {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Delete", "Variety")",
                    data: {
                        VarietyID: id
                    },
                    success: function (data) {
                        if (data.result === "ok") {
                            searchItems();
                        }
                        else {
                            //alert(data.ErrorMessage);
                            showMessage({ content: data.message });
                        }

                    }
                });//End: $.ajax()
            }
        }

    </script>
}

Production/Views/Variety/_List.cshtml
@model IPagedList<Production.DataAccess.Variety>


<table style="width: 100%; margin-bottom: 15px;" class="table table-striped" id="tblRegistration">
    <thead>
        <tr>
            <th>
                <a href="#" onclick="sortBy('VarietyName'); return false;">@ResourceBL.GetText("Variety Name")</a>
            </th>
            <th>
                <a href="#" onclick="sortBy('VarietyCode'); return false;">@ResourceBL.GetText("Variety Code")</a>
            </th>
            <th>
                <a href="#" onclick="sortBy('Customer.CustomerID'); return false;">@ResourceBL.GetText("Customer")</a>
            </th>
            <th>
                <span href="#">@ResourceBL.GetText("Actions")</span>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.Raw(item.VarietyName)
                </td>
                <td>
                    @Html.Raw(item.VarietyCode)
                </td>
                <td>
                    @Html.Raw(item.CustomerName)
                </td>
                <td>
                    <i class="fa fa-edit"></i><a href="javascript:void(0);" onclick="editItem(@item.VarietyID)">@ResourceBL.GetText("Edit")</a> |
                    <i class="fa fa-remove"></i><a href="javascript:void(0);" onclick="deleteItem(@item.VarietyID)">@ResourceBL.GetText("Delete")</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@if (Model.PageCount > 1) {
    <div class="paging">
        @Html.Pager(Model.PageSize, Model.PageIndex + 1, Model.TotalItemCount, new AjaxOptions() { UpdateTargetId = "dvUsers" }).Options(o => o
        .RouteValues(new
        {
            pageSize = ViewBag.pageSize
        }))
    </div>
}